model_list:
  - model_name: os.environ/MODEL_NAME
    litellm_params:
      model: os.environ/MODEL_PROVIDER
      api_base: os.environ/MODEL_URL
      api_key: os.environ/MODEL_API_KEY

litellm_settings:
  callbacks: ["proxy.custom_callback.proxy_handler_instance"]

router_settings:
  enable_pre_call_checks: false

environment_variables:
  METRICS_JSONL: os.environ/METRICS_JSONL
